name: 'Action Toolkit InnerSource'
description: 'Action that provides repositories with the necessary tools and documentation for an innersource work model'
inputs:
  GH_TOKEN:  #ID de token GitHub
    description: 'Token GitHub'
    required: true
    #default: 'World'
#outputs:
#  time: # id of output
#    description: 'The time we greeted you'
#runs:
#  using: 'node16'
#  main: 'index.js'
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: |
        ls
        cd..
        ls
    - name: Add-Labels
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
      run: addlabels.sh
      shell: bash
      
      
