name: 'Action Toolkit InnerSource'
description: 'Action that provides repositories with the necessary tools and documentation for an innersource work model'
inputs:
  GH_TOKEN:  #ID de token GitHub
    description: 'Token GitHub'
    required: true
    #default: 'World'
#outputs:
#  time: # id of output
#    description: 'The time we greeted you'
#runs:
#  using: 'node16'
#  main: 'index.js'
runs:
  using: "composite"
  steps:
    - name: Step1
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
      run: |
        #git branch
        #ls
        #gh label list
        #gh label create prueba --description "prueba action" --color E99695
        url_file_labels="https://raw.githubusercontent.com/bancolombia/action-innersource-toolkit/0a126b4e10487a1037e0f4e5eb57f08844176d37/Configurations/labels.txt"
        #curl -s "$url_file_labels"
        IFS=" "
        curl -s "$url_file_labels"
        while read -r line;
        do
         IFS_antiguo=$IFS
         IFS=";" 
         read -ra partes <<< "$line"
         IFS=$IFS_antiguo
         echo "${partes[0]}"
        done
      shell: bash
      
      
