name: 'Action Toolkit InnerSource'
description: 'Action that provides repositories with the necessary tools and documentation for an innersource work model'
inputs:
  GH_TOKEN:  #ID de token GitHub
    description: 'Token GitHub'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: add labels
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
      run: addlabels.sh
      shell: bash
    - name: add type issues
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
      run: addtypeissues.sh
      shell: bash

      
      
