name: 'Action Toolkit InnerSource'
description: 'Action that provides repositories with the necessary tools and documentation for an innersource work model'
#inputs:
#  who-to-greet:  # id of input
#    description: 'Who to greet'
#    required: true
#    default: 'World'
#outputs:
#  time: # id of output
#    description: 'The time we greeted you'
#runs:
#  using: 'node16'
#  main: 'index.js'
runs:
  using: "composite"
  steps:
    - run: git branch
      shell: bash
